#!/bin/sh /etc/rc.common
# by chuacw 18 Apr 2018

START=18
cmd="/usr/sbin/dnscrypt-proxy"
name=$(basename $(readlink -f $cmd))
stdout_log="/var/log/$name.log"
pid_file="/var/run/$name.pid"
stderr_log="/var/log/$name.err"
arguments="-config /etc/config/dnscrypt-proxy.toml -logfile $stdout_log"
start_cmd="start-stop-daemon -b -S -m -p $pid_file -x $name -- $arguments"
stop_cmd="start-stop-daemon -K -p $pid_file"

echo "dnscrypt-proxy init.d script (c) 2018 chuacw - https://github.com/chuacw"

EXTRA_COMMANDS="status"
EXTRA_HELP="	status  Shows the status"

status() {
  echo "Checking status"
# check if the file exist, then check if /proc/PID exist
  if [ -f $pid_file ] && [ -d /proc/$(eval "cat $pid_file") ]
  then
    echo "DNScrypt proxy running..."
    eval echo "Process ID: " $(cat $pid_file)
  else
    echo "DNScrypt proxy not running..."
  fi
}

start() {
  echo "Starting DNSCrypt proxy..."
  $start_cmd
  echo "See ps result for confirmation"
  ps | grep "$name"
}

stop() {
  echo "Stopping DNSCrypt proxy..."
  if [ -f $pid_file ] && [ -d /proc/$(eval "cat $pid_file") ]
  then
    $stop_cmd
    echo "See ps result below for confirmation"
    ps | grep "$name"
    # redirect stdout including errors
     rm $pid_file &> /dev/null
  else
    echo "DNScrypt proxy not running..."
  fi
}
